= watchlist

== ERD



This project uses Quarkus, the Supersonic Subatomic Java Framework.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/.

== Running the application in dev mode

You can run your application in dev mode that enables live coding using:

[source,shell script]
----
./mvnw quarkus:dev
----

____

*_NOTE:_* Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.

____

== Packaging and running the application

The application can be packaged using:

[source,shell script]
----
./mvnw package
----

It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/quarkus-app/lib/` directory.

The application is now runnable using `java -jar target/quarkus-app/quarkus-run.jar`.

If you want to build an _über-jar_, execute the following command:

[source,shell script]
----
./mvnw package -Dquarkus.package.jar.type=uber-jar
----

The application, packaged as an _über-jar_, is now runnable using `java -jar target/*-runner.jar`.

== Creating a native executable

You can create a native executable using:

[source,shell script]
----
./mvnw package -Dnative
----

Or, if you don't have GraalVM installed, you can run the native executable build in a container using:

[source,shell script]
----
./mvnw package -Dnative -Dquarkus.native.container-build=true
----

You can then execute your native executable with: `./target/watchlist-1.0.0-SNAPSHOT-runner`

If you want to learn more about building native executables, please consult https://quarkus.io/guides/maven-tooling.

== Related Guides

* REST resources for Hibernate ORM with Panache (https://quarkus.io/guides/rest-data-panache[guide]): Generate Jakarta REST resources for your Hibernate Panache entities and repositories
* RESTEasy Classic (https://quarkus.io/guides/resteasy[guide]): REST endpoint framework implementing Jakarta REST and more
* JDBC Driver - PostgreSQL (https://quarkus.io/guides/datasource[guide]): Connect to the PostgreSQL database via JDBC

== Provided Code

=== REST Data with Panache

Generating Jakarta REST resources with Panache

https://quarkus.io/guides/rest-data-panache[Related guide section…]

=== RESTEasy JAX-RS

Easily start your RESTful Web Services

https://quarkus.io/guides/getting-started#the-jax-rs-resources[Related guide section…]