GET localhost:8080/person/1
Accept: Application/json

###
POST localhost:8080/person
Content-Type: application/json

{
  "personId":17,
  "firstName":"J",
  "lastName":"D",
  "email":"j.d@email.com"
}


###
GET localhost:8080/person/mostRelevant/actors
Accept: application/json
